name: Tests

on:
  push:
    branches:
      - "**"
      - '!master' # excludes master
    tags-ignore:
      - "*.*"

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
        include:
          - php: 7.4
            scout: 7.0
            testbench: 5.0
            phpunit: 9.5
            opensearch: 1.3.6

          - php: 8.0
            scout: 8.0
            testbench: 6.0
            phpunit: 9.5
            opensearch: 1.3.6

          - php: 8.1
            scout: 9.0
            testbench: 7.0
            phpunit: 9.5
            opensearch: 1.3.6
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install php and composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2

      - name: Install OpenSearch
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: ${{ matrix.opensearch }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer require --no-interaction --with-all-dependencies orchestra/testbench:^${{ matrix.testbench }} phpunit/phpunit:^${{ matrix.phpunit }} laravel/scout:^${{ matrix.scout }}

      - name: Run tests
        run: composer test

